export const CUISINES = [
  { name: "Afghani", id: "afghani_restaurant" },
  { name: "African", id: "african_restaurant" },
  { name: "American", id: "american_restaurant" },
  { name: "Asian", id: "asian_restaurant" },
  { name: "Bar and Grill", id: "bar_and_grill" },
  { name: "Barbecue", id: "barbecue_restaurant" },
  { name: "Brazilian", id: "brazilian_restaurant" },
  { name: "Breakfast", id: "breakfast_restaurant" },
  { name: "Brunch", id: "brunch_restaurant" },
  { name: "Buffet", id: "buffet_restaurant" },
  { name: "Cafeteria", id: "cafeteria" },
  { name: "Chinese", id: "chinese_restaurant" },
  { name: "Dessert", id: "dessert_restaurant" },
  { name: "Diner", id: "diner" },
  { name: "Fast Food", id: "fast_food_restaurant" },
  { name: "Fine Dining", id: "fine_dining_restaurant" },
  { name: "French", id: "french_restaurant" },
  { name: "Greek", id: "greek_restaurant" },
  { name: "Hamburger", id: "hamburger_restaurant" },
  { name: "Indian", id: "indian_restaurant" },
  { name: "Indonesian", id: "indonesian_restaurant" },
  { name: "Italian", id: "italian_restaurant" },
  { name: "Japanese", id: "japanese_restaurant" },
  { name: "Korean", id: "korean_restaurant" },
  { name: "Lebanese", id: "lebanese_restaurant" },
  { name: "Mediterranean", id: "mediterranean_restaurant" },
  { name: "Mexican", id: "mexican_restaurant" },
  { name: "Middle Eastern", id: "middle_eastern_restaurant" },
  { name: "Pizza", id: "pizza_restaurant" },
  { name: "Pub", id: "pub" },
  { name: "Ramen", id: "ramen_restaurant" },
  { name: "Seafood", id: "seafood_restaurant" },
  { name: "Spanish", id: "spanish_restaurant" },
  { name: "Steakhouse", id: "steak_house" },
  { name: "Sushi", id: "sushi_restaurant" },
  { name: "Thai", id: "thai_restaurant" },
  { name: "Turkish", id: "turkish_restaurant" },
  { name: "Vegan", id: "vegan_restaurant" },
  { name: "Vegetarian", id: "vegetarian_restaurant" },
  { name: "Vietnamese", id: "vietnamese_restaurant" },
] as const;
